openapi: 3.2.0
info:
  title: OutRival Rest API
  description: OutRival API documentation.
  version: '1.0'
  contact: {}
servers:
- url: https://api.outrival.com
tags:
- name: Rest
paths:
  /rest/v1/webhooks/vapi/server-messages:
    post:
      operationId: VapiWebhooksController_onServerMessage
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Rest
      summary: Vapi webhooks controller on server message
      x-summary-source: derived
  /rest/v1/webhooks/vapi/custom-llm/chat/completions:
    post:
      operationId: VapiWebhooksController_onOpenAICustomLLMCall
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Rest
      summary: Vapi webhooks controller on open AI custom LLM call
      x-summary-source: derived
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-API-Key
